import type { NextPage } from 'next'
import Head from 'next/head'
import Containers from '../components/Containers'
import styles from '../styles/Home.module.css'



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Containers/>
    </> 
  )
}

export default Home

